(()=>{
const KEY='happy-bingo-license';
const SECRET='HAPPY-BINGO-2026-SELLER-KEY';
const CARD_KEY='happy-bingo-cards';
const PASSWORD='20260817';
const $=s=>document.querySelector(s);
async function sha(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function machineId(){let raw=[navigator.userAgent,navigator.platform,screen.width,screen.height,screen.colorDepth,navigator.language].join('|');return 'HB-'+(await sha(raw+'|'+location.origin)).slice(0,16).toUpperCase()}
async function licenseKey(id){return 'HBG-'+(await sha(id+'|'+SECRET)).slice(0,16).toUpperCase()}
function style(){if($('#final-manager-style'))return;const s=document.createElement('style');s.id='final-manager-style';s.textContent=`#license-gate{position:fixed;inset:0;z-index:999999;background:#06101d;color:#fff;display:flex;align-items:center;justify-content:center;font-family:Arial,sans-serif}#license-gate .box{width:min(520px,92vw);background:#0c1b2c;border:2px solid #f5c84b;border-radius:18px;padding:32px;box-shadow:0 20px 80px #000b}#license-gate h1{margin:0 0 6px;color:#f5c84b}#license-gate p{color:#9db3c5;line-height:1.5}#license-gate code{display:block;background:#050b12;border:1px solid #29415a;border-radius:9px;padding:14px;color:#4dff9b;font-weight:900;letter-spacing:1px;word-break:break-all;margin:14px 0}#license-gate input,#license-gate button,#fb-modal input{width:100%;box-sizing:border-box;padding:13px;border-radius:9px;margin-top:10px;font-size:15px}#license-gate input,#fb-modal input{background:#07131f;color:#fff;border:1px solid #35516b}#license-gate button,#fb-modal button{border:0;background:#16a66a;color:#fff;font-weight:900;cursor:pointer}.gate-error{color:#ff6670;margin-top:10px;font-weight:800}#fb-launch{position:fixed;left:18px;bottom:18px;z-index:8000;background:#f59e0b;color:#111;border:0;border-radius:9px;padding:12px 16px;font-weight:1000;box-shadow:0 8px 30px #0007;cursor:pointer}#fb-modal{position:fixed;inset:0;z-index:99998;background:#000b;display:flex;align-items:center;justify-content:center;color:#fff;font-family:Arial,sans-serif}#fb-modal .panel{width:min(720px,94vw);max-height:90vh;overflow:auto;background:#0b1725;border:2px solid #f5c84b;border-radius:16px;padding:22px}#fb-modal h2{margin:0;color:#f5c84b}#fb-modal .toolbar{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}#fb-modal .toolbar button{width:auto;padding:10px 15px;margin:0}#fb-modal .grid{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.fb-cell{aspect-ratio:1;text-align:center;font-size:22px;font-weight:1000;border-radius:8px;border:2px solid #334e68;background:#fff;color:#111}.fb-cell.free{background:#f5c84b}.fb-note{color:#9db3c5;font-size:12px;margin:8px 0}.fb-close{background:#7d1820!important}.fb-status{color:#4dff9b;font-weight:900;margin:8px 0}`;document.head.appendChild(s)}
function cards(){try{const c=JSON.parse(localStorage.getItem(CARD_KEY)||'null');if(Array.isArray(c)&&c.length===100)return c}catch{}return Array.from({length:100},(_,i)=>({id:i+1,values:Array(25).fill(0)}))}
function valid(v){if(v.length!==25||v[12]!==0)return false;const ranges=[[1,15],[16,30],[31,45],[46,60],[61,75]];for(let c=0;c<5;c++){const seen=new Set;for(let r=0;r<5;r++){let i=r*5+c;if(i===12)continue;let n=Number(v[i]),[a,b]=ranges[c];if(!Number.isInteger(n)||n<a||n>b||seen.has(n))return false;seen.add(n)}}return true}
function openBuilder(){let c=cards(),idx=0;const m=document.createElement('div');m.id='fb-modal';m.innerHTML=`<div class="panel"><h2>Cartella Builder</h2><div class="fb-note">Manager password verified. Edit Cartella 001–100. B 1–15 · I 16–30 · N 31–45 · G 46–60 · O 61–75 · center is FREE.</div><div class="toolbar"><button id="fb-prev">← Previous</button><button id="fb-next">Next →</button><button id="fb-random">Generate Random</button><button id="fb-save">SAVE CARTELLA</button><button class="fb-close" id="fb-close">CLOSE</button></div><div class="fb-status" id="fb-status"></div><div class="grid" id="fb-grid"></div></div>`;document.body.appendChild(m);const grid=$('#fb-grid'),status=$('#fb-status');function render(){const v=c[idx].values;grid.innerHTML='';for(let i=0;i<25;i++){const x=document.createElement('input');x.className='fb-cell'+(i===12?' free':'');x.value=i===12?'FREE':(v[i]||'');x.disabled=i===12;x.inputMode='numeric';x.addEventListener('input',e=>{c[idx].values[i]=Number(e.target.value)||0});grid.appendChild(x)}status.textContent=`CARTELLA ${String(c[idx].id).padStart(3,'0')} / 100`};function random(){const ranges=[[1,15],[16,30],[31,45],[46,60],[61,75]];const v=Array(25).fill(0);ranges.forEach(([a,b],col)=>{const pool=Array.from({length:b-a+1},(_,i)=>a+i).sort(()=>Math.random()-.5).slice(0,5);pool.forEach((n,row)=>v[row*5+col]=n)});v[12]=0;c[idx].values=v;render()}$('#fb-prev').onclick=()=>{if(idx){idx--;render()}};$('#fb-next').onclick=()=>{if(idx<99){idx++;render()}};$('#fb-random').onclick=random;$('#fb-save').onclick=()=>{if(!valid(c[idx].values)){status.textContent='INVALID CARTELLA — fix the ranges/duplicates';status.style.color='#ff6670';return}localStorage.setItem(CARD_KEY,JSON.stringify(c));status.textContent=`CARTELLA ${String(c[idx].id).padStart(3,'0')} SAVED`;status.style.color='#4dff9b'};$('#fb-close').onclick=()=>m.remove();render()}
async function launch(){style();const id=await machineId();const validKey=await licenseKey(id);if(localStorage.getItem(KEY)!==validKey){const g=document.createElement('div');g.id='license-gate';g.innerHTML=`<div class="box"><h1>HAPPY BINGO</h1><p>License activation is required before using this machine.</p><b>Machine ID</b><code>${id}</code><input id="license-input" placeholder="Enter your license key" autocomplete="off"><button id="activate">ACTIVATE LICENSE</button><div id="gate-error" class="gate-error"></div><p style="font-size:12px">Send the Machine ID to the Happy Bingo seller to receive the activation key.</p></div>`;document.body.appendChild(g);$('#activate').onclick=()=>{const k=$('#license-input').value.trim().toUpperCase();if(k!==validKey){$('#gate-error').textContent='Invalid license key for this machine.';return}localStorage.setItem(KEY,validKey);g.remove();location.reload()};return}
const b=document.createElement('button');b.id='fb-launch';b.textContent='CARTELLA BUILDER';b.onclick=()=>{const p=prompt('MANAGER PASSWORD');if(p===PASSWORD)openBuilder();else if(p!==null)alert('Incorrect manager password.')};document.body.appendChild(b)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',launch);else launch();
})();
