(()=>{
const KEY='happy-bingo-license';
const SECRET='HAPPY-BINGO-2026-SELLER-KEY';
const CARD_KEY='happy-bingo-cards';
const SETS_KEY='happy-bingo-card-sets';
const CURRENT_SET_KEY='happy-bingo-current-set';
const PASSWORD='20260817';
const $=s=>document.querySelector(s);
async function sha(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function machineId(){let raw=[navigator.userAgent,navigator.platform,screen.width,screen.height,screen.colorDepth,navigator.language].join('|');return 'HB-'+(await sha(raw+'|'+location.origin)).slice(0,16).toUpperCase()}
async function licenseKey(id){return 'HBG-'+(await sha(id+'|'+SECRET)).slice(0,16).toUpperCase()}
function valid(v){if(!Array.isArray(v)||v.length!==25||v[12]!==0)return false;const ranges=[[1,15],[16,30],[31,45],[46,60],[61,75]];for(let c=0;c<5;c++){const seen=new Set;for(let r=0;r<5;r++){let i=r*5+c;if(i===12)continue;let n=Number(v[i]),[a,b]=ranges[c];if(!Number.isInteger(n)||n<a||n>b||seen.has(n))return false;seen.add(n)}}return true}
function validCards(c){return Array.isArray(c)&&c.length===100&&c.every(x=>x&&Number.isInteger(x.id)&&valid(x.values))}
function newCards(seed=Date.now()){const cards=[];for(let id=1;id<=100;id++){const cols=[];for(let col=0;col<5;col++){const a=Array.from({length:15},(_,i)=>col*15+i+1);let s=(seed+id*31+col*17)>>>0;for(let i=a.length-1;i>0;i--){s=(s*1664525+1013904223)>>>0;const j=s%(i+1);[a[i],a[j]]=[a[j],a[i]]}cols.push(a.slice(0,5))}cards.push({id,values:Array.from({length:25},(_,i)=>i===12?0:cols[i%5][Math.floor(i/5)])})}return cards}
function readSets(){try{const x=JSON.parse(localStorage.getItem(SETS_KEY)||'null');if(x&&typeof x==='object')return x}catch{}return {}}
function writeSets(x){localStorage.setItem(SETS_KEY,JSON.stringify(x))}
function currentSetId(){return localStorage.getItem(CURRENT_SET_KEY)||''}
function currentSet(){const sets=readSets();const id=currentSetId();return id&&validCards(sets[id]?.cards)?sets[id]:null}
function bootstrapSets(){const sets=readSets();let id=currentSetId();const existing=(()=>{try{return JSON.parse(localStorage.getItem(CARD_KEY)||'null')}catch{return null}})();if(id&&validCards(sets[id]?.cards)){localStorage.setItem(CARD_KEY,JSON.stringify(sets[id].cards));return}if(validCards(existing)){id='HB-001';sets[id]={id,cards:existing,createdAt:sets[id]?.createdAt||new Date().toISOString()};writeSets(sets);localStorage.setItem(CURRENT_SET_KEY,id);return}localStorage.setItem(CARD_KEY,JSON.stringify(Array.from({length:100},(_,i)=>({id:i+1,values:Array(25).fill(0)}))));localStorage.removeItem(CURRENT_SET_KEY)}
function selectSet(id){const sets=readSets();if(!validCards(sets[id]?.cards))return false;localStorage.setItem(CURRENT_SET_KEY,id);localStorage.setItem(CARD_KEY,JSON.stringify(sets[id].cards));return true}
function createSet(){const sets=readSets();const nums=Object.keys(sets).map(k=>Number(k.replace('HB-',''))).filter(Number.isFinite);const next=(nums.length?Math.max(...nums):0)+1;const id=`HB-${String(next).padStart(3,'0')}`;sets[id]={id,cards:newCards(Date.now()),createdAt:new Date().toISOString()};writeSets(sets);selectSet(id);return id}
function style(){if($('#final-manager-style'))return;const s=document.createElement('style');s.id='final-manager-style';s.textContent=`#license-gate{position:fixed;inset:0;z-index:999999;background:#06101d;color:#fff;display:flex;align-items:center;justify-content:center;font-family:Arial,sans-serif}#license-gate .box{width:min(520px,92vw);background:#0c1b2c;border:2px solid #f5c84b;border-radius:18px;padding:32px;box-shadow:0 20px 80px #000b}#license-gate h1{margin:0 0 6px;color:#f5c84b}#license-gate p{color:#9db3c5;line-height:1.5}#license-gate code{display:block;background:#050b12;border:1px solid #29415a;border-radius:9px;padding:14px;color:#4dff9b;font-weight:900;letter-spacing:1px;word-break:break-all;margin:14px 0}#license-gate input,#license-gate button{width:100%;box-sizing:border-box;padding:13px;border-radius:9px;margin-top:10px;font-size:15px}#license-gate input{background:#07131f;color:#fff;border:1px solid #35516b}#license-gate button{border:0;background:#16a66a;color:#fff;font-weight:900;cursor:pointer}.gate-error{color:#ff6670;margin-top:10px;font-weight:800}#fb-launch{display:none}#sets-panel{margin-top:16px;padding:16px;border-radius:14px;background:linear-gradient(135deg,#0b243d,#102b1f);border:2px solid #2c8a5d;color:#fff}#sets-panel h3{margin:0 0 10px;color:#f5c84b;font-size:18px}#sets-current{padding:12px;border-radius:10px;background:#07131f;border:1px solid #1b4a3a;margin-bottom:12px}#sets-list{display:grid;gap:8px;margin-top:10px;max-height:180px;overflow:auto}.set-row{display:flex;justify-content:space-between;align-items:center;gap:10px;padding:10px 12px;background:#0e1e30;border:1px solid #29415a;border-radius:9px}.set-row strong{color:#4dff9b}.set-row small{color:#9db3c5}.set-row button,#sets-panel button{border:0;border-radius:8px;padding:9px 12px;font-weight:900;cursor:pointer}.set-use{background:#16a66a;color:#fff}.set-new{background:#f59e0b;color:#111}.set-print{background:#2563eb;color:#fff}.set-builder{background:#7c3aed;color:#fff}.sets-actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}.set-note{font-size:11px;color:#9db3c5;margin-top:8px;line-height:1.4}.set-msg{font-size:12px;font-weight:900;color:#4dff9b;margin-top:8px}`;document.head.appendChild(s)}
function builder(){let c=currentSet()?.cards||(()=>{try{return JSON.parse(localStorage.getItem(CARD_KEY)||'[]')}catch{return []}})();if(!validCards(c))c=newCards(Date.now());let idx=0;const m=document.createElement('div');m.id='fb-modal';m.innerHTML=`<div class="panel"><h2 style="color:#f5c84b">Cartella Builder</h2><div class="fb-note">Set ${currentSetId()||'UNASSIGNED'} · Manager password verified. Edit Cartella 001–100. B 1–15 · I 16–30 · N 31–45 · G 46–60 · O 61–75 · center is FREE.</div><div class="toolbar"><button id="fb-prev">← Previous</button><button id="fb-next">Next →</button><button id="fb-random">Generate Random</button><button id="fb-save">SAVE CARTELLA</button><button id="fb-close" class="fb-close">CLOSE</button></div><div class="fb-status" id="fb-status"></div><div class="grid" id="fb-grid"></div></div>`;document.body.appendChild(m);const grid=$('#fb-grid'),status=$('#fb-status');function render(){const v=c[idx].values;grid.innerHTML='';for(let i=0;i<25;i++){const x=document.createElement('input');x.className='fb-cell'+(i===12?' free':'');x.value=i===12?'FREE':(v[i]||'');x.disabled=i===12;x.inputMode='numeric';x.addEventListener('input',e=>{c[idx].values[i]=Number(e.target.value)||0});grid.appendChild(x)}status.textContent=`CARTELLA ${String(c[idx].id).padStart(3,'0')} / 100 · SET ${currentSetId()||'UNASSIGNED'}`}function random(){c[idx].values=newCards(Date.now()+idx)[idx].values;render()}$('#fb-prev').onclick=()=>{if(idx){idx--;render()}};$('#fb-next').onclick=()=>{if(idx<99){idx++;render()}};$('#fb-random').onclick=random;$('#fb-save').onclick=()=>{if(!valid(c[idx].values)){status.textContent='INVALID CARTELLA — fix ranges/duplicates';status.style.color='#ff6670';return}const id=currentSetId();if(!id||!currentSet()){status.textContent='CREATE OR SELECT A CARTELLA SET FIRST';status.style.color='#ff6670';return}const sets=readSets();sets[id].cards=c;writeSets(sets);localStorage.setItem(CARD_KEY,JSON.stringify(c));status.textContent=`CARTELLA ${String(c[idx].id).padStart(3,'0')} SAVED TO ${id}`;status.style.color='#4dff9b'}$('#fb-close').onclick=()=>m.remove();render()}
function injectSetsPanel(root){if(root.querySelector('#sets-panel'))return;const panel=document.createElement('section');panel.id='sets-panel';panel.innerHTML=`<h3>🎫 CARTELLA SETS</h3><div id="sets-current"></div><div id="sets-list"></div><div class="sets-actions"><button class="set-new" id="set-new">+ CREATE NEW SET</button><button class="set-builder" id="set-builder">🔐 CARTELLA BUILDER</button><button class="set-print" id="set-print">📄 PRINT / DOWNLOAD CURRENT SET</button></div><div class="set-note">Opening Happy Bingo never creates a new set. Printing never creates new cards. Only CREATE NEW SET makes new Cartellas.</div><div class="set-msg" id="set-msg"></div>`;root.appendChild(panel);const cur=panel.querySelector('#sets-current'),list=panel.querySelector('#sets-list'),msg=panel.querySelector('#set-msg');function render(){const sets=readSets();const id=currentSetId();cur.innerHTML=id&&sets[id]?`<strong>CURRENT SET: ${id}</strong><br><small>${sets[id].cards.length} saved Cartellas · Created ${new Date(sets[id].createdAt).toLocaleString()}</small>`:`<strong>NO CARTELLA SET SELECTED</strong><br><small>Create a set before starting a game.</small>`;list.innerHTML=Object.keys(sets).sort().map(k=>`<div class="set-row"><div><strong>${k}</strong><br><small>100 saved Cartellas</small></div><button class="set-use" data-set="${k}">${k===id?'CURRENT':'USE'}</button></div>`).join('');list.querySelectorAll('[data-set]').forEach(b=>b.onclick=()=>{selectSet(b.dataset.set);render();msg.textContent=`${b.dataset.set} selected. Cards are unchanged.`});}
panel.querySelector('#set-new').onclick=()=>{const id=createSet();render();msg.textContent=`${id} created and selected. These cards are now fixed until you edit them.`};panel.querySelector('#set-builder').onclick=()=>{const p=prompt('MANAGER PASSWORD');if(p===PASSWORD)builder();else if(p!==null)alert('Incorrect manager password.')};panel.querySelector('#set-print').onclick=async()=>{const curSet=currentSet();if(!curSet)return msg.textContent='Select or create a Cartella Set first.';try{await window.happyBingo?.generateCardsPdf?.(curSet.cards,curSet.id);msg.textContent=`Printed/downloaded exact saved set ${curSet.id}.` }catch(e){msg.textContent='Could not print current Cartella Set.';console.error(e)}};render()}
function observeSettings(){const obs=new MutationObserver(()=>{const root=document.querySelector('.colorful-settings');if(root)injectSetsPanel(root)});obs.observe(document.body,{childList:true,subtree:true});setInterval(()=>{const root=document.querySelector('.colorful-settings');if(root)injectSetsPanel(root)},700)}
function wrapPdfBridge(){const b=window.happyBingo;if(!b?.generateCardsPdf||b.generateCardsPdf.__setWrapped)return;const original=b.generateCardsPdf.bind(b);const wrapped=(cards,setId)=>{const c=currentSet();if(c)return original(c.cards,c.id);return original(cards,setId)};wrapped.__setWrapped=true;b.generateCardsPdf=wrapped}
async function launch(){style();bootstrapSets();observeSettings();wrapPdfBridge();const id=await machineId();const validKey=await licenseKey(id);if(localStorage.getItem(KEY)!==validKey){const g=document.createElement('div');g.id='license-gate';g.innerHTML=`<div class="box"><h1>HAPPY BINGO</h1><p>License activation is required before using this machine.</p><b>Machine ID</b><code>${id}</code><input id="license-input" placeholder="Enter your license key" autocomplete="off"><button id="activate">ACTIVATE LICENSE</button><div id="gate-error" class="gate-error"></div><p style="font-size:12px">Send the Machine ID to the Happy Bingo seller to receive the activation key.</p></div>`;document.body.appendChild(g);$('#activate').onclick=()=>{const k=$('#license-input').value.trim().toUpperCase();if(k!==validKey){$('#gate-error').textContent='Invalid license key for this machine.';return}localStorage.setItem(KEY,validKey);g.remove();location.reload()};return}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',launch);else launch();
})();
