(()=>{
const CARD_KEY='happy-bingo-cards',SETS_KEY='happy-bingo-card-sets',CURRENT_SET_KEY='happy-bingo-current-set';
function readSets(){try{const x=JSON.parse(localStorage.getItem(SETS_KEY)||'null');if(x&&typeof x==='object')return x}catch{}return{}}
function cards(){try{const c=JSON.parse(localStorage.getItem(CARD_KEY)||'null');if(Array.isArray(c)&&c.length===100)return c}catch{}return[]}
function valid(v){if(!Array.isArray(v)||v.length!==25||v[12]!==0)return false;const ranges=[[1,15],[16,30],[31,45],[46,60],[61,75]];for(let c=0;c<5;c++){const seen=new Set();for(let r=0;r<5;r++){const i=r*5+c;if(i===12)continue;const n=Number(v[i]),[a,b]=ranges[c];if(!Number.isInteger(n)||n<a||n>b||seen.has(n))return false;seen.add(n)}}return true}
function validCards(c){return Array.isArray(c)&&c.length===100&&c.every(x=>x&&Number.isInteger(x.id)&&valid(x.values))}
function bootstrap(){const sets=readSets(),id=localStorage.getItem(CURRENT_SET_KEY)||'';if(id&&validCards(sets[id]?.cards)){localStorage.setItem(CARD_KEY,JSON.stringify(sets[id].cards));return}const existing=cards();if(validCards(existing)){const setId=id||'HB-001';sets[setId]={id:setId,cards:existing,createdAt:sets[setId]?.createdAt||new Date().toISOString()};localStorage.setItem(CURRENT_SET_KEY,setId);localStorage.setItem(CARD_KEY,JSON.stringify(existing));localStorage.setItem(SETS_KEY,JSON.stringify(sets))}}
function style(){if(document.getElementById('customer-cartella-style'))return;const st=document.createElement('style');st.id='customer-cartella-style';st.textContent=`.customer-cartella-hidden{display:none!important}#customer-cartella-readonly{margin-top:14px;padding:14px 16px;border:1px solid #29415a;border-radius:12px;background:#0b1725;color:#fff}#customer-cartella-readonly strong{color:#4dff9b}#customer-cartella-readonly small{display:block;margin-top:4px;color:#8fa6b8}`;document.head.appendChild(st)}
function cleanSettings(){const modal=document.querySelector('.colorful-settings');if(!modal)return;if(!modal.querySelector('#customer-cartella-readonly')){const panel=document.createElement('section');panel.id='customer-cartella-readonly';const setId=localStorage.getItem(CURRENT_SET_KEY)||'';panel.innerHTML=setId?`<strong>CARTELLA SET: ${setId}</strong><small>100 saved Cartellas installed for this machine.</small>`:`<strong>CARTELLA SET</strong><small>No installed Cartella Set. Contact the seller.</small>`;modal.querySelector('.settings-grid')?.appendChild(panel)}modal.querySelectorAll('.settings-card.blue,.settings-action.lock,.settings-action.pdf').forEach(el=>el.classList.add('customer-cartella-hidden'));modal.querySelectorAll('.setting-row').forEach(el=>{if(el.querySelector('select'))el.classList.add('customer-cartella-hidden')});modal.querySelectorAll('#sets-panel,#fb-modal').forEach(el=>el.remove())}
function start(){bootstrap();style();const obs=new MutationObserver(cleanSettings);obs.observe(document.documentElement,{childList:true,subtree:true});cleanSettings()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();