import { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'
import './professional-cleanup.css'

const LETTERS = ['B','I','N','G','O'] as const
const RANGES: Record<string,[number,number]> = { B:[1,15], I:[16,30], N:[31,45], G:[46,60], O:[61,75] }
const MANAGER_PASSWORD = '20260817'
type Card={id:number;values:number[]}; type Called={letter:string;number:number}

declare global { interface Window { happyBingo?: { playVoice:(file:string)=>Promise<string>; generateCardsPdf?:()=>Promise<{cards:Card[];path:string}> } } }
const getLetter=(n:number)=>n<=15?'B':n<=30?'I':n<=45?'N':n<=60?'G':'O'
const pool=()=>Array.from({length:75},(_,i)=>i+1)
const ring=(n:number)=>n<=15?'border-[#E51C24]':n<=30?'border-[#00A3E0]':n<=45?'border-[#FF9900]':n<=60?'border-[#A100FF]':'border-[#00C853]'
const emptyCard=(id:number):Card=>({id,values:Array.from({length:25},(_,i)=>i===12?0:0)})
function generateCards(){return Array.from({length:100},(_,id)=>{const cols=LETTERS.map(letter=>{const [a,b]=RANGES[letter];const v=Array.from({length:b-a+1},(_,i)=>a+i);let s=(id+1)*97+a*31;for(let i=v.length-1;i>0;i--){s=(s*1664525+1013904223)>>>0;const j=s%(i+1);[v[i],v[j]]=[v[j],v[i]]}return v.slice(0,5)});return{id:id+1,values:Array.from({length:25},(_,i)=>i===12?0:cols[i%5][Math.floor(i/5)])}})}
function loadCards(){try{const x=JSON.parse(localStorage.getItem('happy-bingo-cards')||'null');if(Array.isArray(x)&&x.length===100)return x as Card[]}catch{}const x=generateCards();localStorage.setItem('happy-bingo-cards',JSON.stringify(x));return x}
function validCard(c:Card){for(let r=0;r<5;r++){const seen=new Set<number>();for(let col=0;col<5;col++){if(r===2&&col===2)continue;const n=c.values[r*5+col],[a,b]=RANGES[LETTERS[col]];if(!Number.isInteger(n)||n<a||n>b||seen.has(n))return false;seen.add(n)}}return c.values[12]===0}
function BingoCell({number,isCalled}:{number:number;isCalled:boolean}){return <div className="w-12 h-12 flex items-center justify-center bg-[#182030] border border-[#202b40]">{isCalled?<div className={`w-10 h-10 rounded-full bg-white border-[3px] ${ring(number)} flex items-center justify-center shadow-md ring-2 ring-white ring-inset`}><span className="text-black font-black text-sm">{number}</span></div>:<span className="text-slate-400 font-bold text-sm">{number}</span>}</div>}
function audioPlay(url:string,rate:number){return new Promise<void>((resolve,reject)=>{const a=new Audio(url);a.preload='auto';a.volume=1;a.playbackRate=rate;a.onended=()=>resolve();a.onerror=()=>reject(new Error('Audio could not be played'));a.play().catch(reject)})}

function App(){
 const [cards,setCards]=useState<Card[]>(loadCards),[selected,setSelected]=useState<Set<number>>(new Set()),[started,setStarted]=useState(false),[paused,setPaused]=useState(false),[called,setCalled]=useState<Called[]>([]),[remaining,setRemaining]=useState(pool),[voicePlaying,setVoicePlaying]=useState(false),[voiceSpeed,setVoiceSpeed]=useState(()=>Number(localStorage.getItem('happy-bingo-voice-speed')||'1')),[callGap,setCallGap]=useState(()=>Number(localStorage.getItem('happy-bingo-call-gap')||'3')),[voiceEnabled,setVoiceEnabled]=useState(()=>localStorage.getItem('happy-bingo-voice')!=='off'),[settings,setSettings]=useState(false),[builder,setBuilder]=useState(false),[builderIndex,setBuilderIndex]=useState(0),[draft,setDraft]=useState<Card>(()=>loadCards()[0]||emptyCard(1)),[password,setPassword]=useState(''),[unlocked,setUnlocked]=useState(false),[message,setMessage]=useState(''),[check,setCheck]=useState(false),[verify,setVerify]=useState(''),[inspection,setInspection]=useState<number|null>(null),[winning,setWinning]=useState<number[]>([]),[winner,setWinner]=useState<number|null>(null),[locked,setLocked]=useState<Set<number>>(new Set()),[bet,setBet]=useState(()=>localStorage.getItem('happy-bingo-bet')||''),[cut,setCut]=useState(()=>localStorage.getItem('happy-bingo-cut')||''),[money,setMoney]=useState(()=>Number(localStorage.getItem('happy-bingo-total-money-made')||'0'))
 const calledSet=useMemo(()=>new Set(called.map(x=>x.number)),[called]),current=called[0]
 const saveCards=(x:Card[])=>{setCards(x);localStorage.setItem('happy-bingo-cards',JSON.stringify(x))}
 const notify=(x:string)=>{setMessage(x);window.setTimeout(()=>setMessage(''),3000)}
 const playVoice=async(file:string)=>{if(!voiceEnabled)return true;if(!window.happyBingo?.playVoice)return false;setVoicePlaying(true);try{const url=await window.happyBingo.playVoice(file);await audioPlay(url,voiceSpeed);return true}catch{return false}finally{setVoicePlaying(false)}}
 const start=async()=>{if(!selected.size)return notify('Select at least one cartella.');setCalled([]);setRemaining(pool());setPaused(false);setLocked(new Set());setWinner(null);setInspection(null);setWinning([]);setStarted(true);await playVoice('chewatawu.mp3')}
 const togglePause=async()=>{if(!started)return;if(paused){setPaused(false);await playVoice('chewatawu.mp3')}else{setPaused(true);await playVoice('pause.mp3')}}
 const draw=async()=>{if(!started||paused||voicePlaying||!remaining.length)return;const n=remaining[Math.floor(Math.random()*remaining.length)],l=getLetter(n);setRemaining(x=>x.filter(v=>v!==n));setCalled(x=>[{letter:l,number:n},...x]);await playVoice(`${l.toLowerCase()}${n}.mp3`)}
 useEffect(()=>{if(!started||paused||voicePlaying||!remaining.length)return;const t=window.setTimeout(()=>void draw(),called.length?Math.max(.5,callGap)*1000:700);return()=>clearTimeout(t)},[started,paused,voicePlaying,remaining.length,called.length,callGap])
 const lines=(c:Card)=>{const m=c.values.map((n,i)=>i===12||calledSet.has(n));const rows=Array.from({length:5},(_,r)=>Array.from({length:5},(_,c)=>r*5+c));const cols=Array.from({length:5},(_,c)=>Array.from({length:5},(_,r)=>r*5+c));return[...rows,...cols,[0,6,12,18,24],[4,8,12,16,20],[0,4,20,24]].filter(x=>x.every(i=>m[i]))}
 const checkWinner=async()=>{const id=Number(verify),c=cards.find(x=>x.id===id);if(!c||id<1||id>100)return notify('Enter a cartella number from 001 to 100.');if(!selected.has(id))return notify(`Cartella ${String(id).padStart(3,'0')} is not selected.`);setInspection(id);if(locked.has(id)){await playVoice('cartellawu.mp3');return notify('Cartella is locked.')}const win=lines(c);setWinning(win.flat());setCheck(false);if(!win.length){setLocked(x=>new Set(x).add(id));await playVoice('cartellawu.mp3');return notify('No valid bingo. Cartella locked.')}setWinner(id);await playVoice('Goodbingo.mp3');const gain=Number(bet||0);if(gain>0){const next=money+gain;setMoney(next);localStorage.setItem('happy-bingo-total-money-made',String(next))}}
 const unlock=()=>{if(password===MANAGER_PASSWORD){setUnlocked(true);setPassword('');setBuilder(true);setSettings(false);setDraft(cards[builderIndex]||emptyCard(builderIndex+1))}else notify('Incorrect manager password.')}
 const edit=(i:number,v:string)=>{const x=v===''?0:Number(v);setDraft(c=>({...c,values:c.values.map((n,j)=>j===i?x:n)}))}
 const saveDraft=()=>{if(!validCard(draft))return notify('Cartella values are not valid for B, I, N, G and O.');const x=[...cards];x[builderIndex]=draft;saveCards(x);notify(`Cartella ${String(draft.id).padStart(3,'0')} saved.`)}
 const nextCard=()=>{const i=Math.min(99,builderIndex+1);setBuilderIndex(i);setDraft(cards[i]||emptyCard(i+1))};const prevCard=()=>{const i=Math.max(0,builderIndex-1);setBuilderIndex(i);setDraft(cards[i]||emptyCard(i+1))}
 return <div className="app-shell">
 <header className="topbar"><div className="brand">HAPPY <span>BINGO</span></div><div className="top-actions"><span className="ready-pill">{started?'LIVE':'READY'}</span><span className="counter">{called.length}/75</span><button className="top-button" onClick={()=>setSettings(true)}>SETTINGS</button><button className="top-button" onClick={()=>void togglePause()}>{paused?'RESUME':'PAUSE'}</button><button className="top-button" onClick={()=>void draw()}>DRAW BALL</button><button className="danger-button" onClick={()=>{setStarted(false);setPaused(false);setCalled([]);setRemaining(pool())}}>END</button></div></header>
 <section className="call-banner"><div className="current-ball">{current?`${current.letter} ${current.number}`:'—'}</div><div className="recent-calls">{called.slice(1,5).map(c=><div className={`recent-ball ${ring(c.number)}`} key={c.number}>{c.letter}{c.number}</div>)}</div></section>
 <main className="master-board"><div className="board-header"><span>MASTER CALLER</span><span>{called.length}/75 CALLED</span></div><div className="master-grid">{Array.from({length:75},(_,i)=><BingoCell key={i+1} number={i+1} isCalled={calledSet.has(i+1)}/>)}</div></main>
 <div className="bottom-controls"><button onClick={()=>setCheck(true)}>CHECK</button>{!started&&<button onClick={()=>void start()}>START GAME</button>}<button onClick={()=>void draw()}>DRAW BALL</button><button onClick={()=>void togglePause()}>{paused?'RESUME':'PAUSE'}</button></div>
 {inspection&&<div className="inspection-panel"><h3>CARTELLA {String(inspection).padStart(3,'0')}</h3><div className="inspection-grid">{cards.find(c=>c.id===inspection)?.values.map((n,i)=><div key={i} className={winning.includes(i)?'win-cell':calledSet.has(n)||i===12?'called-cell':'normal-cell'}>{i===12?'FREE':n}</div>)}</div>{winner===inspection&&<strong>BINGO</strong>}</div>}
 {check&&<div className="modal-overlay"><div className="check-modal"><button onClick={()=>setCheck(false)}>×</button><h2>CHECK</h2><label>Card Number</label><input value={verify} onChange={e=>setVerify(e.target.value.replace(/\D/g,''))}/><button className="check-action" onClick={()=>void checkWinner()}>CHECK WIN</button></div></div>}
 {settings&&<div className="modal-overlay"><div className="settings-modal"><button onClick={()=>setSettings(false)}>×</button><h2>SETTINGS</h2><label>Voice <button onClick={()=>setVoiceEnabled(x=>{localStorage.setItem('happy-bingo-voice',x?'on':'off');return !x})}>{voiceEnabled?'ON':'OFF'}</button></label><label>Voice Speed <input type="number" min=".75" max="1.5" step=".05" value={voiceSpeed} onChange={e=>{const v=Number(e.target.value);setVoiceSpeed(v);localStorage.setItem('happy-bingo-voice-speed',String(v))}}/></label><label>Calling Gap (seconds) <input type="number" min=".5" max="15" step=".5" value={callGap} onChange={e=>{const v=Number(e.target.value);setCallGap(v);localStorage.setItem('happy-bingo-call-gap',String(v))}}/></label><label>Bet Amount <input value={bet} onChange={e=>{setBet(e.target.value);localStorage.setItem('happy-bingo-bet',e.target.value)}}/></label><label>Cut Percentage <input value={cut} onChange={e=>{setCut(e.target.value);localStorage.setItem('happy-bingo-cut',e.target.value)}}/></label><div>Total Bingo Made <b>{money} Birr</b></div><hr/><h3>CARTELLA BUILDER</h3>{!unlocked?<><input inputMode="numeric" type="password" placeholder="Manager password" value={password} onChange={e=>setPassword(e.target.value.replace(/\D/g,''))}/><button onClick={unlock}>UNLOCK</button></>:<button onClick={()=>{setSettings(false);setBuilder(true)}}>OPEN BUILDER</button>}</div></div>}
 {builder&&<div className="modal-overlay"><div className="settings-modal builder-modal"><button onClick={()=>setBuilder(false)}>×</button><h2>CARTELLA {String(draft.id).padStart(3,'0')}</h2><div className="builder-head">{LETTERS.map(x=><b key={x}>{x}</b>)}</div><div className="builder-grid">{draft.values.map((n,i)=>i===12?<div className="builder-free" key={i}>FREE</div>:<input key={i} inputMode="numeric" value={n||''} onChange={e=>edit(i,e.target.value.replace(/\D/g,''))}/>)}</div><div className="builder-actions"><button onClick={prevCard}>PREVIOUS</button><button onClick={saveDraft}>SAVE CARTELLA</button><button onClick={nextCard}>NEXT</button></div></div></div>}
 {message&&<div className="toast">{message}</div>}
 </div>
}
createRoot(document.getElementById('root')!).render(<App />)
