import { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'
import './game-overrides.css'

const LETTERS = ['B', 'I', 'N', 'G', 'O'] as const
const CARD_COUNT = 100
const RANGES: Record<string, [number, number]> = { B: [1, 15], I: [16, 30], N: [31, 45], G: [46, 60], O: [61, 75] }
const MANAGER_PASSWORD = '20260817'

type Card = { id: number; values: number[] }
type Called = { letter: string; number: number }

declare global { interface Window { happyBingo?: { generateCardsPdf?: () => Promise<{ cards: Card[]; path: string }>; playVoice?: (file: string) => Promise<string> } } }

const getLetter = (n: number) => n <= 15 ? 'B' : n <= 30 ? 'I' : n <= 45 ? 'N' : n <= 60 ? 'G' : 'O'
const makePool = () => Array.from({ length: 75 }, (_, i) => i + 1)
const rowColor = (n: number) => n <= 15 ? 'border-[#E51C24]' : n <= 30 ? 'border-[#00A3E0]' : n <= 45 ? 'border-[#FF9900]' : n <= 60 ? 'border-[#A100FF]' : 'border-[#00C853]'

function BingoCell({ number, isCalled }: { number: number; isCalled: boolean }) {
  return <div className="w-12 h-12 flex items-center justify-center bg-[#182030] border border-[#202b40] relative">
    {isCalled ? <div className={`w-10 h-10 rounded-full bg-white border-[3px] ${rowColor(number)} flex items-center justify-center shadow-md ring-2 ring-white ring-inset`}><span className="text-black font-black text-sm">{number}</span></div> : <span className="text-slate-400 font-bold text-sm">{number}</span>}
  </div>
}

function generateCards(): Card[] { return Array.from({ length: CARD_COUNT }, (_, id) => { const cols = LETTERS.map(letter => { const [min, max] = RANGES[letter]; const values = Array.from({ length: max - min + 1 }, (_, i) => min + i); let seed = (id + 1) * 97 + min * 31; for (let i = values.length - 1; i > 0; i--) { seed = (seed * 1664525 + 1013904223) >>> 0; const j = seed % (i + 1); [values[i], values[j]] = [values[j], values[i]] } return values.slice(0, 5) }); return { id: id + 1, values: Array.from({ length: 25 }, (_, i) => i === 12 ? 0 : cols[i % 5][Math.floor(i / 5)]) } }) }
function loadCards(): Card[] { try { const saved = JSON.parse(localStorage.getItem('happy-bingo-cards') || 'null'); if (Array.isArray(saved) && saved.length === 100) return saved } catch {} const cards = generateCards(); localStorage.setItem('happy-bingo-cards', JSON.stringify(cards)); return cards }
function playAudio(fileUrl: string, rate: number): Promise<void> { return new Promise(resolve => { const audio = new Audio(); let settled = false; const finish = () => { if (!settled) { settled = true; audio.onended = null; audio.onerror = null; resolve() } }; audio.preload = 'auto'; audio.playbackRate = rate; audio.onended = finish; audio.onerror = finish; audio.src = fileUrl; audio.load(); void audio.play().catch(finish) }) }
function makeEmptyCard(id: number): Card { return { id, values: Array.from({ length: 25 }, (_, i) => i === 12 ? 0 : 0) } }
function cardComplete(card: Card) { return card.values.every((n, i) => i === 12 || Number.isInteger(n) && n > 0) }
function cardValid(card: Card) { if (!cardComplete(card)) return false; for (let row = 0; row < 5; row++) { const seen = new Set<number>(); for (let col = 0; col < 5; col++) { const n = card.values[row * 5 + col]; const [min, max] = RANGES[LETTERS[col]]; if (n < min || n > max || seen.has(n)) return false; seen.add(n) } } return card.values[12] === 0 }

function App() {
  const [cards, setCards] = useState<Card[]>(loadCards), [selected, setSelected] = useState<Set<number>>(new Set()), [started, setStarted] = useState(false), [paused, setPaused] = useState(false), [called, setCalled] = useState<Called[]>([]), [remaining, setRemaining] = useState(makePool), [locked, setLocked] = useState<Set<number>>(new Set()), [voicePlaying, setVoicePlaying] = useState(false), [voiceEnabled, setVoiceEnabled] = useState(() => localStorage.getItem('happy-bingo-voice') !== 'off'), [voiceSpeed, setVoiceSpeed] = useState(() => Number(localStorage.getItem('happy-bingo-voice-speed') || '1')), [callGap, setCallGap] = useState(() => Number(localStorage.getItem('happy-bingo-call-gap') || '3')), [settingsOpen, setSettingsOpen] = useState(false), [cardSource, setCardSource] = useState<'printed'|'pdf'>(() => (localStorage.getItem('happy-bingo-card-source') as 'printed'|'pdf') || 'printed'), [generatingPdf, setGeneratingPdf] = useState(false), [message, setMessage] = useState(''), [checkOpen, setCheckOpen] = useState(false), [verifyInput, setVerifyInput] = useState(''), [winner, setWinner] = useState<number|null>(null), [inspectionCard, setInspectionCard] = useState<number|null>(null), [winningIndexes, setWinningIndexes] = useState<number[]>([]), [betAmount, setBetAmount] = useState(() => localStorage.getItem('happy-bingo-bet') || ''), [cutPercent, setCutPercent] = useState(() => localStorage.getItem('happy-bingo-cut') || ''), [totalMoneyMade, setTotalMoneyMade] = useState(() => Math.max(0, Number(localStorage.getItem('happy-bingo-total-money-made') || '0'))), [manualSetup, setManualSetup] = useState(() => localStorage.getItem('happy-bingo-manual-setup') === 'on'), [setupIndex, setSetupIndex] = useState(0), [draftCard, setDraftCard] = useState<Card>(() => loadCards()[0] || makeEmptyCard(1))
  const current = called[0] || null; const calledSet = useMemo(() => new Set(called.map(item => item.number)), [called]); const currentAmount = betAmount === '' ? null : selected.size * Number(betAmount || 0)
  async function playVoice(file: string) { if (!voiceEnabled || !window.happyBingo?.playVoice) return; setVoicePlaying(true); try { const fileUrl = await window.happyBingo.playVoice(file); await playAudio(fileUrl, voiceSpeed) } catch { setMessage(`VOICE ERROR: ${file}`) } finally { setVoicePlaying(false) } }
  function toggleCard(id:number){ if(started)return; setSelected(prev=>{const next=new Set(prev); next.has(id)?next.delete(id):next.add(id); return next}) }
  async function startGame(){ if(!selected.size)return setMessage('Select at least one cartella.'); setCalled([]);setRemaining(makePool());setLocked(new Set());setPaused(false);setWinner(null);setInspectionCard(null);setWinningIndexes([]);setVerifyInput('');setCheckOpen(false);setMessage('');setStarted(true);await playVoice('chewatawu.mp3') }
  async function callNext(){ if(!started||paused||!remaining.length||voicePlaying)return; const number=remaining[Math.floor(Math.random()*remaining.length)],letter=getLetter(number);setRemaining(prev=>prev.filter(v=>v!==number));setCalled(prev=>[{letter,number},...prev]);await playVoice(`${letter.toLowerCase()}${number}.mp3`) }
  useEffect(()=>{if(!started||paused||voicePlaying||!remaining.length)return;const timer=window.setTimeout(()=>{void callNext()},called.length===0?900:Math.max(.5,callGap)*1000);return()=>window.clearTimeout(timer)},[started,paused,voicePlaying,remaining.length,called.length,callGap])
  function getWinningLines(card:Card){ const marked=card.values.map((n,i)=>i===12||calledSet.has(n)); const rows=Array.from({length:5},(_,r)=>Array.from({length:5},(_,c)=>r*5+c)); const cols=Array.from({length:5},(_,c)=>Array.from({length:5},(_,r)=>r*5+c)); const diagonals=[[0,6,12,18,24],[4,8,12,16,20]]; const corners=[[0,4,20,24]]; return [...rows,...cols,...diagonals,...corners].filter(line=>line.every(i=>marked[i])) }
  async function checkWinner(){const id=Number(verifyInput),card=cards.find(item=>item.id===id);if(!Number.isInteger(id)||id<1||id>100||!card)return setMessage('Enter a valid cartella number from 001 to 100.');if(!selected.has(id))return setMessage(`Cartella ${String(id).padStart(3,'0')} is not active.`);if(!cardValid(card))return setMessage('Cartella is not configured correctly.');setInspectionCard(id);if(locked.has(id)){await playVoice('cartellawu.mp3');setCheckOpen(false);return setMessage(`CARTELLA ${String(id).padStart(3,'0')} IS LOCKED.`)}const lines=getWinningLines(card);setWinningIndexes(lines.flat());setCheckOpen(false);if(!lines.length){setLocked(prev=>new Set(prev).add(id));await playVoice('cartellawu.mp3');return setMessage(`CARTELLA ${String(id).padStart(3,'0')} LOCKED — INVALID BINGO.`)}await playVoice('Goodbingo.mp3');setWinner(id)}
  function saveCards(next:Card[]){setCards(next);localStorage.setItem('happy-bingo-cards',JSON.stringify(next))}
  function saveBet(v:string){setBetAmount(v);v===''?localStorage.removeItem('happy-bingo-bet'):localStorage.setItem('happy-bingo-bet',v)} function saveCut(v:string){setCutPercent(v);v===''?localStorage.removeItem('happy-bingo-cut'):localStorage.setItem('happy-bingo-cut',v)} function saveVoiceSpeed(v:number){setVoiceSpeed(v);localStorage.setItem('happy-bingo-voice-speed',String(v))} function saveCallGap(v:number){setCallGap(v);localStorage.setItem('happy-bingo-call-gap',String(v))}
  function openManualSetup(){const password=window.prompt('MANAGER PASSWORD\nEnter the numeric password to open Cartella Building:');if(password!==MANAGER_PASSWORD)return setMessage('Incorrect manager password.');setManualSetup(true);localStorage.setItem('happy-bingo-manual-setup','on');setSetupIndex(0);setDraftCard(cards[0]||makeEmptyCard(1));setSettingsOpen(false)}
  return <div className="app-shell"><header className="topbar"><div className="brand">HAPPY <span>BINGO</span></div><div className="top-actions"><span className="ready-pill">● {started?'LIVE':'READY'}</span><span className="counter">{called.length}/75</span><button className="top-button" onClick={()=>setSettingsOpen(true)}>SETTING</button><button className="top-button" onClick={()=>setPaused(p=>!p)}>{paused?'RESUME':'PAUSE'}</button><button className="top-button" onClick={()=>void callNext()}>DRAW BALL</button><button className="danger-button" onClick={()=>{setStarted(false);setCalled([]);setRemaining(makePool());setPaused(false)}}>END</button></div></header>
  <section className="call-banner"><div className="current-ball">{current?`${current.letter} ${current.number}`:'—'}</div><div className="recent-calls">{called.slice(1,5).map((c,i)=><div className={`recent-ball ${rowColor(c.number)}`} key={`${c.number}-${i}`}>{c.letter}{c.number}</div>)}</div></section>
  <main className="master-board"><div className="board-header"><span>MASTER CALLER</span><span>{called.length}/75 CALLED</span></div><div className="master-grid">{LETTERS.map(letter=><div className={`letter-badge ${letter.toLowerCase()}`} key={letter}>{letter}</div>)}{Array.from({length:15},(_,col)=>LETTERS.map((letter,row)=>{const number=row*15+col+1;return <BingoCell key={number} number={number} isCalled={calledSet.has(number)}/> }))}</div></main>
  {checkOpen&&<div className="modal-overlay"><div className="check-modal"><button onClick={()=>setCheckOpen(false)}>×</button><h2>CHECK</h2><label>Card Number</label><input value={verifyInput} onChange={e=>setVerifyInput(e.target.value.replace(/\D/g,''))}/><button className="check-action" onClick={()=>void checkWinner()}>CHECK WIN</button></div></div>}
  {settingsOpen&&<div className="modal-overlay"><div className="settings-modal"><button onClick={()=>setSettingsOpen(false)}>×</button><h2>SETTINGS</h2><label>Voice Speed <input type="number" min=".75" max="1.5" step=".05" value={voiceSpeed} onChange={e=>saveVoiceSpeed(Number(e.target.value))}/></label><label>Calling Gap (seconds) <input type="number" min=".5" max="10" step=".5" value={callGap} onChange={e=>saveCallGap(Number(e.target.value))}/></label><label>Bet Amount <input value={betAmount} onChange={e=>saveBet(e.target.value)}/></label><label>Cut Percentage <input value={cutPercent} onChange={e=>saveCut(e.target.value)}/></label><div>Total Bingo Made: <b>{totalMoneyMade} Birr</b></div><button onClick={openManualSetup}>FILL CARTELLA SETTING</button></div></div>}
  {inspectionCard&&<div className="inspection-panel"><h3>CARTELLA {String(inspectionCard).padStart(3,'0')}</h3><div className="inspection-grid">{cards.find(c=>c.id===inspectionCard)?.values.map((n,i)=><div className={winningIndexes.includes(i)?'win-cell':calledSet.has(n)||i===12?'called-cell':'normal-cell'} key={i}>{i===12?'FREE':n}</div>)}</div>{winner&&<strong>🏆 BINGO — CARTELLA {String(winner).padStart(3,'0')}</strong>}</div>}
  <div className="bottom-controls"><button onClick={()=>setSettingsOpen(true)}>SETTING</button><button onClick={()=>setCheckOpen(true)}>CHECK</button><button onClick={()=>void callNext()}>DRAW BALL</button><button onClick={()=>setPaused(p=>!p)}>{paused?'RESUME':'PAUSE'}</button></div>
  {message&&<div className="toast">{message}</div>}</div>
}

createRoot(document.getElementById('root')!).render(<App />)
