(() => {
  const PASSWORD = '20260817'
  const CARDS_KEY = 'happy-bingo-cards'
  const MONEY_KEY = 'happy-bingo-bingo-made'
  const ranges = [[1,15],[16,30],[31,45],[46,60],[61,75]]
  const letters = ['B','I','N','G','O']
  const money = () => Number(localStorage.getItem(MONEY_KEY) || '0') || 0
  const addMoney = amount => { if (amount > 0) localStorage.setItem(MONEY_KEY, String(money() + amount)) }
  const selectedCount = () => document.querySelectorAll('.cartella.selected').length
  const getCards = () => { try { const c = JSON.parse(localStorage.getItem(CARDS_KEY) || '[]'); return Array.isArray(c) && c.length === 100 ? c : [] } catch { return [] } }
  const saveCards = c => localStorage.setItem(CARDS_KEY, JSON.stringify(c))
  const getCard = id => getCards().find(x => x.id === id)
  const validCard = card => {
    if (!card || !Array.isArray(card.values) || card.values.length !== 25) return false
    for (let col=0; col<5; col++) { const [min,max]=ranges[col], seen=new Set(); for(let row=0;row<5;row++){const idx=row*5+col,n=Number(card.values[idx]);if(idx===12)continue;if(!Number.isInteger(n)||n<min||n>max||seen.has(n))return false;seen.add(n)} }
    return Number(card.values[12])===0
  }
  const blankCard = id => ({id, values:Array.from({length:25},(_,i)=>i===12?0:0)})
  const close = el => el?.remove()

  function passwordGate(success) {
    if(document.querySelector('.hb-password-backdrop'))return
    const o=document.createElement('div');o.className='hb-password-backdrop';o.innerHTML='<div class="hb-password-card"><div class="hb-password-icon">🔒</div><div class="hb-password-kicker">MANAGER ONLY</div><h2>Cartella Building</h2><p>Enter the manager password to create or edit the 100 Cartellas.</p><input id="hb-pass" type="password" inputmode="numeric" maxlength="12" placeholder="Manager password"/><div class="hb-password-error" hidden>Incorrect password.</div><div class="hb-password-actions"><button data-cancel>CANCEL</button><button class="confirm" data-ok>UNLOCK</button></div></div>';document.body.appendChild(o)
    const input=o.querySelector('#hb-pass'),err=o.querySelector('.hb-password-error'),submit=()=>{if(input.value!==PASSWORD){err.hidden=false;input.focus();input.select();return}close(o);success()};o.querySelector('[data-cancel]').onclick=()=>close(o);o.querySelector('[data-ok]').onclick=submit;input.onkeydown=e=>{if(e.key==='Enter')submit()};input.focus()
  }

  function builder(){
    let index=0;let cards=getCards();if(cards.length!==100){cards=Array.from({length:100},(_,i)=>blankCard(i+1));saveCards(cards)}
    let draft={id:1,values:[...cards[0].values]};const o=document.createElement('div');o.className='hb-builder-backdrop';o.innerHTML='<div class="hb-builder"><div class="hb-builder-head"><div><span>HAPPY BINGO</span><small>MANAGER • CARTELLA BUILDING</small><h2>Cartella <b id="hb-card-num">001</b></h2></div><button data-close>×</button></div><div class="hb-builder-rules">B 1–15 • I 16–30 • N 31–45 • G 46–60 • O 61–75 • CENTER = FREE</div><div class="hb-builder-grid" id="hb-builder-grid"></div><div class="hb-builder-message" id="hb-builder-message"></div><div class="hb-builder-footer"><span>Cartella <b id="hb-progress">1</b> / 100</span><button id="hb-save" class="save-next">SAVE & NEXT</button></div></div>';document.body.appendChild(o)
    const grid=o.querySelector('#hb-builder-grid'),msg=o.querySelector('#hb-builder-message')
    const render=()=>{o.querySelector('#hb-card-num').textContent=String(index+1).padStart(3,'0');o.querySelector('#hb-progress').textContent=String(index+1);grid.innerHTML='';letters.forEach((letter,col)=>{const column=document.createElement('div');column.className='hb-builder-col';const head=document.createElement('div');head.className=`hb-builder-letter ${letter.toLowerCase()}`;head.textContent=letter;column.appendChild(head);for(let row=0;row<5;row++){const idx=row*5+col;if(idx===12){const free=document.createElement('div');free.className='hb-builder-cell free';free.textContent='FREE';column.appendChild(free)}else{const input=document.createElement('input');input.className='hb-builder-cell';input.type='number';input.inputMode='numeric';input.min=String(ranges[col][0]);input.max=String(ranges[col][1]);input.value=draft.values[idx]?String(draft.values[idx]):'';input.oninput=e=>{draft.values[idx]=e.target.value===''?0:Number(e.target.value)};column.appendChild(input)}}grid.appendChild(column)});msg.textContent=''}
    o.querySelector('[data-close]').onclick=()=>close(o)
    o.querySelector('#hb-save').onclick=()=>{if(!validCard(draft)){msg.textContent='Fill all 24 numbers correctly. No duplicates within a B/I/N/G/O column.';return}cards[index]={id:index+1,values:[...draft.values]};saveCards(cards);if(index===99){msg.textContent='ALL 100 CARTELLAS SAVED.';setTimeout(()=>location.reload(),700);return}index++;draft={id:index+1,values:[...cards[index].values]};render()}
    render()
  }

  function updateMoney(){document.querySelectorAll('[data-hb-bingo-made]').forEach(el=>{const s=el.querySelector('strong');if(s)s.textContent=`${Math.round(money()).toLocaleString()} BIRR`})}
  function addBingoMade(){const modal=document.querySelector('.settings-modal');if(!modal||modal.querySelector('[data-hb-bingo-made]'))return;const box=document.createElement('section');box.className='hb-money-card';box.setAttribute('data-hb-bingo-made','true');box.innerHTML='<div class="hb-money-title">💰 BINGO MADE</div><strong>0 BIRR</strong><small>Manager cut accumulated from completed games. Read-only.</small>';const managerSection=[...modal.querySelectorAll('section')].find(s=>/MANAGER CUT/i.test(s.textContent||''));(managerSection||modal).appendChild(box);updateMoney()}
  const calledNumbers=()=>{const s=new Set();document.querySelectorAll('.number-cell.called span').forEach(el=>{const n=Number(el.textContent);if(n)s.add(n)});return s}
  const winLines=[...Array.from({length:5},(_,r)=>({type:'horizontal',row:r,indices:[0,1,2,3,4].map(c=>r*5+c)})),...Array.from({length:5},(_,c)=>({type:'vertical',col:c,indices:[0,1,2,3,4].map(r=>r*5+c)})),{type:'diag-down',indices:[0,6,12,18,24]},{type:'diag-up',indices:[4,8,12,16,20]},{type:'four-corners',indices:[0,4,20,24]}]
  function checkOverlay(){if(document.querySelector('.hb-check-backdrop'))return;const o=document.createElement('div');o.className='hb-check-backdrop';o.innerHTML='<div class="hb-check-box"><div class="hb-check-kicker">MANAGER CHECK</div><h2>CHECK CARTELLA</h2><p>Enter the Cartella number.</p><input id="hb-check-id" inputmode="numeric" maxlength="3" placeholder="001"/><button class="hb-check-go">CHECK WIN</button><button class="hb-check-cancel">CANCEL</button></div>';document.body.appendChild(o);const input=o.querySelector('#hb-check-id');const run=()=>{const id=Number(input.value),card=getCard(id);if(!card||!validCard(card)){input.value='';input.placeholder='INVALID';input.focus();return}const called=calledNumbers(),marked=card.values.map((n,i)=>i===12||called.has(Number(n))),wins=winLines.filter(l=>l.indices.every(i=>marked[i])),winning=new Set(wins.flatMap(x=>x.indices));const r=document.createElement('div');r.className='hb-result-backdrop';r.innerHTML=`<div class="hb-result"><div class="hb-result-title">CARTELLA ${String(id).padStart(3,'0')}</div><div class="hb-result-card"><div class="hb-result-grid" id="hb-result-grid"></div><div class="hb-shapes" id="hb-shapes"></div></div><div class="hb-result-status ${wins.length?'valid':'invalid'}">${wins.length?'✓ VALID BINGO':'✕ NOT BINGO'}</div><button class="hb-result-close">CLOSE</button></div>`;document.body.appendChild(r);close(o);const g=r.querySelector('#hb-result-grid');card.values.forEach((n,i)=>{const c=document.createElement('div');c.className=`hb-result-cell ${marked[i]?'called':''} ${winning.has(i)?'winning':''}`;c.textContent=i===12?'FREE':String(n);g.appendChild(c)});const sh=r.querySelector('#hb-shapes');wins.forEach(w=>{const line=document.createElement('div');line.className=`hb-shape ${w.type}`;if(w.type==='horizontal')line.style.top=`${w.row*20+10}%`;if(w.type==='vertical')line.style.left=`${w.col*20+10}%`;sh.appendChild(line)});r.querySelector('.hb-result-close').onclick=()=>close(r)};o.querySelector('.hb-check-go').onclick=run;o.querySelector('.hb-check-cancel').onclick=()=>close(o);input.onkeydown=e=>{if(e.key==='Enter')run()};input.focus()}
  document.addEventListener('click',e=>{const b=e.target instanceof Element?e.target.closest('button'):null;if(!b)return;const t=(b.textContent||'').trim();if(/CARTELLA BUILDER|FILL CARTELLA SETTING/i.test(t)){e.preventDefault();e.stopImmediatePropagation();passwordGate(builder);return}if(t==='CHECK'&&document.querySelector('.bingo-mode')){e.preventDefault();e.stopImmediatePropagation();checkOverlay();return}if(/^END$/i.test(t)){const count=selectedCount(),bet=Number(localStorage.getItem('happy-bingo-bet')||0),cut=Number(localStorage.getItem('happy-bingo-cut')||0);addMoney(Math.max(0,count*bet*cut/100));setTimeout(updateMoney,100)}},true)
  new MutationObserver(()=>{addBingoMade();updateMoney()}).observe(document.documentElement,{childList:true,subtree:true});setTimeout(addBingoMade,300)
})()
